name: ${project.name}
main: me.Fupery.PlayerJobs.PlayerJobs
version: ${project.version}
description: ${project.description}
depends: [Vault]
author: Fupery
permissions:
  playerjobs.employer:
    description: Allows players to create jobs
    default: op
  playerjobs.override:
    description: Allows players to delete jobs
    default: op
  playerjobs.admin:
    description: Allows creation and deletion of jobs
    children:
      playerjobs.employer: true
      playerjobs.override: true